pipeline:
  publish:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: drone:5000/cicd-helloworld
    registry: drone:5000
    insecure: true
    tags: "${DRONE_BUILD_NUMBER}"
  deploy:
    image:  devnetsandbox/kube
    kubernetes_server: http://master:8001
    kubernetes_token: <Your Kubernetes Token>
    namespace: default
    deployment: demo-app-cicd
    container: cicd-helloworld
    repo: drone:5000/cicd-helloworld
    registry: drone:5000
    insecure: true
    tag: "${DRONE_BUILD_NUMBER}"
