---

- hosts: localhost
  gather_facts: false

  roles:

    - role: admission_token
      tags:
        - token

  tasks:

    - debug:
        var: admission_token
      tags:
        - token

- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"

  become: true

  roles:

    - role: kubeadm_install
      tags:
        - repo
        - master
        - nodes          

  tasks:

    # Implements Step 2 of http://kubernetes.io/docs/getting-started-guides/kubeadm/

    - name: Initialize master
      command: kubeadm init --token {{ hostvars.localhost.admission_token }} --use-kubernetes-version v1.5.4
      args:
        creates: /etc/kubernetes/pki
      register: master_init
      ignore_errors: true
      tags:
        - master
        - init

    - debug:
        var: master_init.stdout_lines

      # Not 100% sure that the creates clause is correct

- hosts: "{{ hostvars.localhost.groups.nodes | join(',') }}"

  become: true

  roles:

    - role: kubeadm_install
      tags:
        - repo
        - master
        - nodes    

  tasks:

    # Implements Step 3 of http://kubernetes.io/docs/getting-started-guides/kubeadm/

    - set_fact:
        master_ip_address: '{{ master_ip_address_configured }}'
      when: master_ip_address_configured is defined

    - set_fact:
        master_ip_address: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4']['address'] }}"
      when: master_ip_address_configured is not defined

    - name: Join nodes to cluster
      command: kubeadm join --token {{ hostvars.localhost.admission_token }} {{  master_ip_address }}
      args:
        creates: /etc/kubernetes/kubelet.conf
      register: node_join
      ignore_errors: true
      tags:
        - nodes
        - join

    - debug:
        var: node_join.stdout_lines

      # Not 100% sure that the creates clause is correct

- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"
  become: true
  tasks:
    # Implements Step 4 of http://kubernetes.io/docs/getting-started-guides/kubeadm/

    - name: Download contiv installer
      command: "{{ item }}"
      with_items:
        - curl -L -O https://github.com/contiv/install/releases/download/{{ contiv_ver }}/contiv-{{ contiv_ver }}.tgz 
        - tar zxf contiv-{{ contiv_ver }}.tgz
      register: contiv_download
      tags:
        - master

    - debug:
        var: contiv_download.results

- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"
  become: true
  tasks:
    # Implements Step 4 of http://kubernetes.io/docs/getting-started-guides/kubeadm/
    - name: Install contiv installer
      command: "{{ item }}"
      args: 
        chdir: "/root/contiv-{{ contiv_ver }}"
      with_items:
        - ./install/k8s/install.sh -n {{  master_ip_address }}
      register: pod_network
      ignore_errors: True
      tags:
        - master

    - debug:
        var: pod_network.results

- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"

  become: true

  tasks:

    # Implements Step 4 of http://kubernetes.io/docs/getting-started-guides/kubeadm/
    - wait_for:
        port: 9999
        delay: 10

    - name: Create Contiv default-net
      command: netctl net create --subnet=10.96.0.0/12 --gateway=10.96.0.1 default-net 
      register: create_network
      ignore_errors: True
      tags:
        - master

    - debug:
        var: create_network.stdout_lines

- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"
  become: true
  tasks:
    # start kubectl proxy
    - name: start kubectl proxy
      command: kubectl proxy --address=0.0.0.0 --port=8001 --accept-hosts=^*$ &
      async: 2592000
      poll: 0
      register: kube_proxy
      tags:
        - master

- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"
  become: true
  tasks:
    # setup Kubernetes UI (Dashboard)
    - name: setup Kubernetes Dashboard
      command: "{{ item }}"
      with_items:
        - curl -L -O  https://raw.githubusercontent.com/iceworld/ansible/master/kubernetes-dashboard.yaml
        - kubectl delete deployment/kube-dns -n kube-system
        - kubectl create -f ./kubernetes-dashboard.yaml
      register: kube_dashboard
      ignore_errors: True
      tags:
        - master
    - debug:
        var: kube_dashboard.results

- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"
  become: true
  tasks:
    - pause:
        seconds: 60
    - name: probe dashboard status
      shell: kubectl get pod -n kube-system | grep dashboard | awk '{print $3}'
      register: podresult
      ignore_errors: True
    - debug:
        var: podresult.stdout

    - name: probe contivh1 nodes
      shell: ping 132.1.1.2 -c 3 && ping 132.1.1.3 -c 3 
      register: contivh1
      ignore_errors: True
    - debug:
        var: contivh1.stdout
      
    - name: reset contiv network if dashboard not running
      command: "{{ item }}"
      args:
        chdir: "/root/contiv-{{ contiv_ver }}"
      with_items:
         - ./install/k8s/uninstall.sh -n 10.10.20.1
         - ./install/k8s/install.sh -n 10.10.20.1
      register: reset_contiv
      ignore_errors: True
      when: podresult.stdout.find('Running')==-1 or contivh1|failed
      tags:
        - master
    - debug:
        var: reset_contiv.results    

    - name: reload dashboard if not running
      command: "{{ item }}"
      with_items:
         - kubectl delete -f ./kubernetes-dashboard.yaml
         - kubectl create -f ./kubernetes-dashboard.yaml
      register: reset_dashboard
      ignore_errors: True
      tags:
        - master
      when: podresult.stdout.find('Running')==-1 or contivh1|failed
    - debug:


- hosts: "{{ hostvars.localhost.groups.master | join(',') }}"
  become: true
  tasks:
    # setup dummy deployment for hello world app
    - name: setup hello deplyoment
      command: "{{ item }}"
      with_items:
        - curl -L -O https://raw.githubusercontent.com/iceworld/drone/master/demo-app-prod.yaml
        - kubectl create -f ./demo-app-prod.yaml
      register: hello
      ignore_errors: True
      tags:
        - master
    - debug:
        var: hello.results
